In [1]:
import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'
import pandas as pd
import numpy as np
import seaborn as sns
import tensorflow as tf
import math
import matplotlib.pyplot as plt

WARNING:tensorflow:From c:\ProgramData\anaconda3\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
data = pd.read_csv('sign_mnist_train.csv')
data.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,3,107,118,127,134,139,143,146,150,153,...,207,207,207,207,206,206,206,204,203,202
1,6,155,157,156,156,156,157,156,158,158,...,69,149,128,87,94,163,175,103,135,149
2,2,187,188,188,187,187,186,187,188,187,...,202,201,200,199,198,199,198,195,194,195
3,2,211,211,212,212,211,210,211,210,210,...,235,234,233,231,230,226,225,222,229,163
4,13,164,167,170,172,176,179,180,184,185,...,92,105,105,108,133,163,157,163,164,179

In [3]:
data.columns

Index(['label', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780',
       'pixel781', 'pixel782', 'pixel783', 'pixel784'],
      dtype='object', length=785)

In [4]:
y=data['label']
y

0         3
1         6
2         2
3         2
4        13
         ..
27450    13
27451    23
27452    18
27453    17
27454    23
Name: label, Length: 27455, dtype: int64

In [5]:
x = data.drop('label', axis = 1)
x

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,107,118,127,134,139,143,146,150,153,156,...,207,207,207,207,206,206,206,204,203,202
1,155,157,156,156,156,157,156,158,158,157,...,69,149,128,87,94,163,175,103,135,149
2,187,188,188,187,187,186,187,188,187,186,...,202,201,200,199,198,199,198,195,194,195
3,211,211,212,212,211,210,211,210,210,211,...,235,234,233,231,230,226,225,222,229,163
4,164,167,170,172,176,179,180,184,185,186,...,92,105,105,108,133,163,157,163,164,179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27450,189,189,190,190,192,193,193,193,193,194,...,132,165,99,77,52,200,234,200,222,225
27451,151,154,157,158,160,161,163,164,166,167,...,198,198,198,198,198,196,195,195,195,194
27452,174,174,174,174,174,175,175,174,173,173,...,121,196,209,208,206,204,203,202,200,200
27453,177,181,184,185,187,189,190,191,191,190,...,119,56,27,58,102,79,47,64,87,93
27454,179,180,180,180,182,181,182,183,182,182,...,108,132,170,194,214,203,197,205,209,215

In [6]:
x

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,107,118,127,134,139,143,146,150,153,156,...,207,207,207,207,206,206,206,204,203,202
1,155,157,156,156,156,157,156,158,158,157,...,69,149,128,87,94,163,175,103,135,149
2,187,188,188,187,187,186,187,188,187,186,...,202,201,200,199,198,199,198,195,194,195
3,211,211,212,212,211,210,211,210,210,211,...,235,234,233,231,230,226,225,222,229,163
4,164,167,170,172,176,179,180,184,185,186,...,92,105,105,108,133,163,157,163,164,179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27450,189,189,190,190,192,193,193,193,193,194,...,132,165,99,77,52,200,234,200,222,225
27451,151,154,157,158,160,161,163,164,166,167,...,198,198,198,198,198,196,195,195,195,194
27452,174,174,174,174,174,175,175,174,173,173,...,121,196,209,208,206,204,203,202,200,200
27453,177,181,184,185,187,189,190,191,191,190,...,119,56,27,58,102,79,47,64,87,93
27454,179,180,180,180,182,181,182,183,182,182,...,108,132,170,194,214,203,197,205,209,215

In [7]:
x_tensor = tf.convert_to_tensor(x, dtype=tf.float32)
y_tensor = tf.convert_to_tensor(y, dtype=tf.int32)  # Adjust dtype as needed

# Example: Print shape of tensors
print("Features Tensor Shape:", x_tensor.shape)
print("Labels Tensor Shape:", y_tensor.shape)

Features Tensor Shape: (27455, 784)
Labels Tensor Shape: (27455,)

In [8]:
# Assuming x_tensor and y_tensor are your feature and label tensors respectively
# Convert your dataset into numpy arrays (assuming they are not already)
from sklearn.model_selection import train_test_split
x_numpy = x_tensor.numpy()
y_numpy = y_tensor.numpy()

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x_numpy, y_numpy, test_size=0.2, random_state=42)

# Print the shapes of the training and testing sets
print(f"Training set: {x_train.shape}, {y_train.shape}")
print(f"Testing set: {x_test.shape}, {y_test.shape}")

x_train = tf.convert_to_tensor(x_train)
x_test = tf.convert_to_tensor(x_test)
y_train = tf.convert_to_tensor(y_train)
y_test = tf.convert_to_tensor(y_test)

# Create TensorFlow datasets from the numpy arrays
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test))

Training set: (21964, 784), (21964,)
Testing set: (5491, 784), (5491,)

In [11]:
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np

batch_size = 32

train_dataset = train_dataset.batch(batch_size).shuffle(buffer_size=1000)

# Prepare the testing dataset with batch size
test_dataset = test_dataset.batch(batch_size)

# Reshape the input data and normalize pixel values
train_dataset = train_dataset.map(lambda x, y: (tf.reshape(tf.cast(x, tf.float32) / 255.0, (-1, 28, 28, 1)), y))
test_dataset = test_dataset.map(lambda x, y: (tf.reshape(tf.cast(x, tf.float32) / 255.0, (-1, 28, 28, 1)), y))

sobel_filter_x = np.array([[-1, 0, 1],
                            [-2, 0, 2],
                            [-1, 0, 1]], dtype=np.float32)

sobel_filter_y = np.array([[-1, -2, -1],
                            [0, 0, 0],
                            [1, 2, 1]], dtype=np.float32)

gabor_filter = np.array([[1, 2, 1],
                          [2, 4, 2],
                          [1, 2, 1]], dtype=np.float32)

# Reshape filters to match TensorFlow's expected shape (height, width, in_channels, out_channels)
sobel_filter_x = sobel_filter_x[:, :, np.newaxis, np.newaxis]
sobel_filter_y = sobel_filter_y[:, :, np.newaxis, np.newaxis]
gabor_filter = gabor_filter[:, :, np.newaxis, np.newaxis]

# Define and create your custom CNN model
def create_custom_cnn_model():
    model = models.Sequential()

    # Custom Sobel X filter convolutional layer
    model.add(layers.Conv2D(filters=1, kernel_size=(3, 3), strides=(1, 1), padding='same', 
                            activation='relu', use_bias=False, 
                            kernel_initializer=tf.constant_initializer(sobel_filter_x), 
                            input_shape=(28, 28, 1)))
    
    # Custom Sobel Y filter convolutional layer
    model.add(layers.Conv2D(filters=1, kernel_size=(3, 3), strides=(1, 1), padding='same', 
                            activation='relu', use_bias=False, 
                            kernel_initializer=tf.constant_initializer(sobel_filter_y)))

    # Gabor filter convolutional layer
    model.add(layers.Conv2D(filters=1, kernel_size=(3, 3), strides=(1, 1), padding='same', 
                            activation='relu', use_bias=False, 
                            kernel_initializer=tf.constant_initializer(gabor_filter)))
    
    # Additional convolutional layers for feature extraction
    model.add(layers.Conv2D(32, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))

    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))

    # Flatten the output to feed into dense layers
    model.add(layers.Flatten())

    # Dense (fully connected) layers for classification with dropout
    model.add(layers.Dense(128, activation='relu'))
    model.add(layers.Dropout(0.2))  # Dropout layer with dropout rate of 0.2 (20%)
    model.add(layers.Dense(26, activation='softmax'))  # Output layer with 26 classes (A-Z)

    return model

# Create an instance of the custom CNN model
custom_cnn_model = create_custom_cnn_model()

# Display the model summary
custom_cnn_model.summary()

# Compile the model
custom_cnn_model.compile(optimizer='adam',
                         loss='sparse_categorical_crossentropy',
                         metrics=['accuracy'])

batch_size = 32
epochs = 10

# Train the model using the training dataset
custom_cnn_model.fit(train_dataset, epochs=epochs, verbose=1)

# Evaluate the model on the testing dataset
test_loss, test_accuracy = custom_cnn_model.evaluate(test_dataset, verbose=1)
print(f"Test Accuracy: {test_accuracy}")

WARNING:tensorflow:From c:\ProgramData\anaconda3\Lib\site-packages\tf_keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\ProgramData\anaconda3\Lib\site-packages\tf_keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 28, 28, 1)         9

 conv2d_1 (Conv2D)           (None, 28, 28, 1)         9

 conv2d_2 (Conv2D)           (None, 28, 28, 1)         9

 conv2d_3 (Conv2D)           (None, 26, 26, 32)        320

 max_pooling2d (MaxPooling2  (None, 13, 13, 32)        0
 D)

 conv2d_4 (Conv2D)           (None, 11, 11, 64)        18496

 max_pooling2d_1 (MaxPoolin  (None, 5, 5, 64)          0
 g2D)

 flatten (Flatten)           (None, 1600)              0

 dense (Dense)               (None, 128)               204928

 dropout (Dropout)           (None, 128)               0

 dense_1 (Dense)             (None, 26)                3354

=================================================================
Total params: 227125 (887.21 KB)
Trainable params: 227125 (887.21 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
WARNING:tensorflow:From c:\ProgramData\anaconda3\Lib\site-packages\tf_keras\src\optimizers\__init__.py:316: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Epoch 1/10
WARNING:tensorflow:From c:\ProgramData\anaconda3\Lib\site-packages\tensorflow\python\autograph\converters\directives.py:126: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\ProgramData\anaconda3\Lib\site-packages\tf_keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

687/687 [==============================] - 19s 7ms/step - loss: 0.4237 - accuracy: 0.8743
Epoch 2/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0383 - accuracy: 0.9890
Epoch 3/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0291 - accuracy: 0.9908
Epoch 4/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0188 - accuracy: 0.9951
Epoch 5/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0182 - accuracy: 0.9949
Epoch 6/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0165 - accuracy: 0.9951
Epoch 7/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0097 - accuracy: 0.9971
Epoch 8/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0187 - accuracy: 0.9936
Epoch 9/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0082 - accuracy: 0.9975
Epoch 10/10
687/687 [==============================] - 5s 7ms/step - loss: 0.0097 - accuracy: 0.9966
172/172 [==============================] - 1s 2ms/step - loss: 4.7109e-05 - accuracy: 1.0000
Test Accuracy: 1.0

In [15]:

from tensorflow.keras.utils import plot_model


# Assuming `custom_cnn_model` is your trained and fit model
plot_model(custom_cnn_model, to_file='custom_cnn_model.png', show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.